/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        background: '#f8f9ff',
        surface: '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'surface-dim': '#cbdbf5',
        'surface-bright': '#f8f9ff',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#44474f',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        'surface-variant': '#d3e4fe',
        'surface-tint': '#455e8c',
        outline: '#747780',
        'outline-variant': '#c4c6d0',
        primary: '#001637',
        'on-primary': '#ffffff',
        'primary-container': '#0d2b56',
        'on-primary-container': '#7a93c4',
        'inverse-primary': '#aec7fb',
        'primary-fixed': '#d7e2ff',
        'primary-fixed-dim': '#aec7fb',
        'on-primary-fixed': '#001b3f',
        'on-primary-fixed-variant': '#2d4773',
        secondary: '#00677d',
        'on-secondary': '#ffffff',
        'secondary-container': '#50d9fe',
        'on-secondary-container': '#005c70',
        'secondary-fixed': '#b3ebff',
        'secondary-fixed-dim': '#4cd6fb',
        'on-secondary-fixed': '#001f27',
        'on-secondary-fixed-variant': '#004e5f',
        tertiary: '#001c10',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#003320',
        'on-tertiary-container': '#00a874',
        'tertiary-fixed': '#6ffbbe',
        'tertiary-fixed-dim': '#4edea3',
        'on-tertiary-fixed': '#002113',
        'on-tertiary-fixed-variant': '#005236',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        headline: ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
      },
      borderRadius: { '4xl': '2rem' },
      spacing: {
        'space-2xs': '0.25rem',
        'space-xs': '0.5rem',
        'space-sm': '0.75rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
        'gutter-mobile': '1rem',
        'gutter-desktop': '1.5rem',
        'sidebar-width': '17.5rem',
        'soap-rail-width': '26rem',
      },
    },
  },
  plugins: [],
}
